name: Update M3U Playlist

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-playlist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install python deps
        run: |
          pip install requests

      - name: Download playlist
        run: |
          curl -L "https://m3u.8088y.fun/testing.m3u" -o source.m3u

      - name: Check streams
        run: |
          python check_streams.py source.m3u main.m3u

      - name: Commit if changed
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add main.m3u
          git commit -m "Auto update playlist" || echo "No changes"
          git push
